export const data = {
  "Sports Fans": {
    across: {
      1: { clue: "Lawmen at the O.K. Corral", answer: "EARPS", row: 0, col: 0 },
      4: { clue: "Footballs have them", answer: "LACES", row: 0, col: 6 },
      7: {
        clue: "Sports arena with service lines and a net",
        answer: "TENNISCOURT",
        row: 2,
        col: 0,
      },
      8: { clue: "King Kong was a big one", answer: "APE", row: 4, col: 0 },
      10: { clue: "People who hit birdies", answer: "GOLFERS", row: 4, col: 4 },
      13: {
        clue: "Indoor sport with pins and alleys",
        answer: "BOWLING",
        row: 6,
        col: 0,
      },
      17: { clue: "Word on a penny", answer: "ONE", row: 6, col: 8 },
      19: {
        clue: "Sports arena with touchlines and goalkeepers",
        answer: "SOCCERFIELD",
        row: 8,
        col: 0,
      },
      20: {
        clue: "Basketball players make these",
        answer: "SHOTS",
        row: 10,
        col: 0,
      },
      21: { clue: "Don't sit", answer: "STAND", row: 10, col: 6 },
    },
    down: {
      1: { clue: "_____ - base hit", answer: "EXTRA", row: 0, col: 0 },
      2: {
        clue: "Where to practice hitting golf balls",
        answer: "RANGE",
        row: 0,
        col: 2,
      },
      3: { clue: "What batters do", answer: "SWING", row: 0, col: 4 },
      4: { clue: "In the neighborhood", answer: "LOCAL", row: 0, col: 6 },
      5: { clue: "Slide at a waterpark", answer: "CHUTE", row: 0, col: 8 },
      6: { clue: "Places on the internet", answer: "SITES", row: 0, col: 10 },
      9: {
        clue: "Some amateur athletes turn this",
        answer: "PRO",
        row: 4,
        col: 1,
      },
      11: { clue: "Dominate, in sports talk", answer: "OWN", row: 4, col: 5 },
      12: { clue: "Baseball score", answer: "RUN", row: 4, col: 9 },
      13: {
        clue: "There are four on a baseball field",
        answer: "BASES",
        row: 6,
        col: 0,
      },
      14: { clue: "Crazy", answer: "WACKO", row: 6, col: 2 },
      15: { clue: "Deep thinkers get them", answer: "IDEAS", row: 6, col: 4 },
      16: { clue: "Birthday presents", answer: "GIFTS", row: 6, col: 6 },
      17: { clue: "Classical music drama", answer: "OPERA", row: 6, col: 8 },
      18: { clue: "Shutdown", answer: "ENDED", row: 6, col: 10 },
    },
  },
  "Top Dogs": {
    across: {
      1: { clue: "Canine Sound", answer: "BARK", row: 0, col: 0 },
      3: {
        clue: "Orbits the sun",
        answer: "PLANET",
        row: 0,
        col: 5,
      },
      8: { clue: "Tiny dog from Mexico", answer: "CHIHUAHUA", row: 2, col: 2 },
      9: {
        clue: "Short legged hunting dog",
        answer: "BASSETHOUND",
        row: 4,
        col: 0,
      },
      15: {
        clue: "Reddish sporting dog",
        answer: "IRISHSETTER",
        row: 6,
        col: 0,
      },
      21: { clue: "Scooby-Doo's breed", answer: "GREATDANE", row: 8, col: 0 },
      22: { clue: "Main tune of a song", answer: "MELODY", row: 10, col: 0 },
      23: { clue: "Puppy's dinner", answer: "CHOW", row: 10, col: 7 },
    },
    down: {
      1: { clue: "Short writing sample", answer: "BLURB", row: 0, col: 0 },
      2: { clue: "Fun to skip at the lake", answer: "ROCKS", row: 0, col: 2 },
      4: {
        clue: "Do this when someone tells a joke",
        answer: "LAUGH",
        row: 0,
        col: 6,
      },
      5: {
        clue: "First prime minister of India",
        answer: "NEHRU",
        row: 0,
        col: 8,
      },
      6: { clue: "Non-coffee morning drink", answer: "TEA", row: 0, col: 10 },
      7: { clue: "Cats chase", answer: "MICE", row: 1, col: 4 },
      10: { clue: "We breathe it", answer: "AIR", row: 4, col: 1 },
      11: {
        clue: "Last message of the titanic",
        answer: "SOS",
        row: 4,
        col: 3,
      },
      12: { clue: "Tablespoon abbreviation", answer: "TBS", row: 4, col: 5 },
      13: { clue: "October abbreviation", answer: "OCT", row: 4, col: 7 },
      14: { clue: "Opposite of SSW", answer: "NNE", row: 4, col: 9 },
      15: { clue: "Perfection", answer: "IDEAL", row: 6, col: 2 },
      17: { clue: "Detested", answer: "HATED", row: 6, col: 4 },
      18: { clue: "Another word for test", answer: "EXAM", row: 6, col: 6 },
      19: { clue: "Molars", answer: "TEETH", row: 6, col: 8 },
      20: { clue: "Extend a subscription", answer: "RENEW", row: 6, col: 10 },
      21: { clue: "Goo on a shoe", answer: "GUM", row: 8, col: 0 },
    },
  },
  "Wiz Kids": {
    across: {
      1: {
        clue: "Defense Against the Dark ____",
        answer: "ARTS",
        row: 0,
        col: 0,
      },
      3: {
        clue: "Keeper of Keys and Grounds, ______ Hagrid",
        answer: "RUBEUS",
        row: 0,
        col: 5,
      },
      6: { clue: "The boy who lived", answer: "HARRYPOTTER", row: 2, col: 0 },
      9: { clue: "Source of music", answer: "RADIO", row: 4, col: 0 },
      10: {
        clue: "Fred and George created a portable one",
        answer: "SWAMP",
        row: 4,
        col: 6,
      },
      13: {
        clue: "One of Hogwarts founders, creater of Hufflepuff House",
        answer: "HELGA",
        row: 6,
        col: 0,
      },
      15: {
        clue: "Size of a giant",
        answer: "LARGE",
        row: 6,
        col: 6,
      },
      17: {
        clue: "He escaped Azkaban prison",
        answer: "SIRIUSBLACK",
        row: 8,
        col: 0,
      },
      20: {
        clue: "Death ______ (Voldemort's follower)",
        answer: "EATERs",
        row: 10,
        col: 0,
      },
      21: {
        clue: "Where a pet door leads to often",
        answer: "YARD",
        row: 10,
        col: 7,
      },
    },
    down: {
      1: { clue: "Left after a phoenix dies", answer: "ASH", row: 0, col: 0 },
      2: { clue: "The _______ Hat", answer: "SORTING", row: 0, col: 3 },
      3: { clue: "Tie someone up with it", answer: "ROPE", row: 0, col: 5 },
      4: { clue: "Magical Menagerie Pet", answer: "BAT", row: 0, col: 7 },
      5: { clue: "Toss out", answer: "SCRAP", row: 0, col: 10 },
      7: {
        clue: "The Triwizard Tournaments last event was _ ____",
        answer: "AMAZE",
        row: 2,
        col: 1,
      },
      8: {
        clue: "Read these leaves in fortune telling",
        answer: "TEA",
        row: 2,
        col: 8,
      },
      11: { clue: "Ron's last name", answer: "WEASLEY", row: 4, col: 7 },
      12: {
        clue: "Professor Binns teaches it's history",
        answer: "MAGIC",
        row: 4,
        col: 9,
      },
      13: { clue: "Hurry-scurry", answer: "HASTE", row: 6, col: 0 },
      14: { clue: "Roman household god", answer: "LAR", row: 6, col: 2 },
      16: { clue: "Seeks permission", answer: "ASKS", row: 7, col: 5 },
      18: { clue: "Frozen water", answer: "ICE", row: 8, col: 3 },
      19: { clue: "Grade schooler", answer: "KID", row: 8, col: 10 },
    },
  },
  "Dino Delight": {
    across: {
      1: { clue: "Piece of Pizza", answer: "SLICE", row: 0, col: 0 },
      4: {
        clue: "Like some Jurassic Park scenes",
        answer: "SCARY",
        row: 0,
        col: 6,
      },
      7: {
        clue: "Three-horned dinosaur",
        answer: "TRICERATOPS",
        row: 2,
        col: 0,
      },
      11: { clue: "Actor ____ Sandler", answer: "ADAM", row: 4, col: 0 },
      12: { clue: "Jack Sparrow is one", answer: "PIRATE", row: 4, col: 5 },
      15: { clue: "Dinosaur hunters find", answer: "FOSSIL", row: 6, col: 0 },
      18: { clue: "Opposite of GIRLS", answer: "BOYS", row: 6, col: 7 },
      19: {
        clue: "King of the dinosaur",
        answer: "TYRANNOSAUR",
        row: 8,
        col: 0,
      },
      24: {
        clue: "Finish your dinner (2 words)",
        answer: "EATUP",
        row: 10,
        col: 0,
      },
      25: { clue: "Gravy shouldn't be this", answer: "LUMPY", row: 10, col: 6 },
    },
    down: {
      1: { clue: "Dogs first trick", answer: "SIT", row: 0, col: 0 },
      2: {
        clue: "__ _ Ran The Zoo, by Dr. Suess (2 words)",
        answer: "IFI",
        row: 0,
        col: 2,
      },
      3: { clue: "Day before Christmas", answer: "EVE", row: 0, col: 4 },
      4: {
        clue: "Finding Nemo takes place here",
        answer: "SEA",
        row: 0,
        col: 6,
      },
      5: { clue: "Good smell", answer: "AROMA", row: 0, col: 8 },
      6: { clue: "Opposite of NO", answer: "YES", row: 0, col: 10 },
      8: {
        clue: "Way to listen to music with AM/FM",
        answer: "RADIO",
        row: 2,
        col: 1,
      },
      9: { clue: "Opposite of GOES", answer: "COMES", row: 2, col: 3 },
      10: {
        clue: "Another word for tearing up paper",
        answer: "RIP",
        row: 2,
        col: 5,
      },
      13: {
        clue: "People wear these over their pajamas",
        answer: "ROBES",
        row: 4,
        col: 7,
      },
      14: {
        clue: "Happy Birthday __ ___ (2 words)",
        answer: "TOYOU",
        row: 4,
        col: 9,
      },
      16: {
        clue: "Jack ____ could eat no fat",
        answer: "SPRAT",
        row: 6,
        col: 2,
      },
      17: { clue: "Letters between K and O", answer: "LMN", row: 6, col: 5 },
      19: {
        clue: "Use this for saying 'This Little Piggy'",
        answer: "TOE",
        row: 8,
        col: 0,
      },
      20: { clue: "Do this when you are tired", answer: "NAP", row: 8, col: 4 },
      21: { clue: "Hooting Bird", answer: "OWL", row: 8, col: 6 },
      22: { clue: "Ready! ___! Fire!", answer: "AIM", row: 8, col: 8 },
      23: {
        clue: "Beam of light coming from the sun",
        answer: "RAY",
        row: 8,
        col: 10,
      },
    },
  },
};
